config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
 

  resources :home, only: %i[show] do 
    resources :orders, only: %i[new create]
    get 'list', on: :collection
    get 'search', on: :collection
    get 'new_order', on: :collection
  end
  
  resources :orders, only: %i[index show] do
    get 'confirmed', on: :collection
    post 'confirm_event/:status', to: 'orders#confirm_event', as: 'confirm_event'
  end


  namespace :my_company do
    devise_for :owners, controllers: {
      sessions: 'my_company/owners/sessions',
      confirmations: 'my_company/owners/confirmations',
      omniauth: 'my_company/owners/omniauth',
      passwords: 'my_company/owners/passwords',
      registrations: 'my_company/owners/registrations',
      unlocks: 'my_company/owners/unlocks'
    }
  end

  resources :buffet, only: %i[show new create edit update] do
    get 'orders', to: 'buffet#orders', as: 'my_orders'
  end
  
  scope :orders_for_owner do
    get 'order_view/:id', to: 'buffet#order_view', as: 'order_view' 
    post 'confirm_order/:id/:status', to: 'buffet#confirm_order', as: 'confirm_order'

    get 'new_price_order/:id', to: 'price_orders#new', as: 'new_price_order'
    post 'price_orders/:id', to: 'price_orders#create', as: 'price_orders'
  end

  resources :events, only: %i[new create show edit update] do
    resources :price_events, only: %i[new create]
    get 'historic_orders', to: 'events#historic_orders', as: 'historic_orders'
  end

  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    confirmations: 'clients/confirmations',
    omniauth: 'clients/omniauth',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    unlocks: 'clients/unlocks'
  }
  



  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index]
      end
      resources :events, only: %i[show] do
        get 'avaliable_event', on: :member
      end
    end
  end
end

app/models/buffet.rb
class Buffet < ApplicationRecord
  belongs_to :owner
  has_many :events


  validates :owner_id, uniqueness: true
  validates :brand_name, :corporate_name, :register_number, :phone_number, :address, :district,
            :state, :city, :zip_code, :description, :payment_methods, presence: true  
  validates :register_number, numericality: {only_integer: true}
  validates :phone_number, length: { minimum: 10, maximum: 16 }

  validate :register_number_is_valid?

  METHODS = [:pix, :money, :credit_card, :debit_card]



  
  def full_register
    "Buffet #{brand_name} | #{corporate_name} CNPJ: #{register_number} | #{mask_phone_number}"
  end

  def full_address
    "Rua: #{address} | Bairro: #{district} | Cidade: #{city} - #{state} | (CEP: #{zip_code})"
  end

  def full_contact
    "Descrição: #{description} | Forma(s) de pagamento(s): #{payment_methods}"
  end
  
  def mask_phone_number
    "(#{phone_number[0..1]}) #{phone_number[2..-1]}"
  end

  private

  def register_number_is_valid?
    return errors.add :register_number, 'deve conter 14 digítos' if register_number.nil? || register_number.to_s.length != 14
    errors.add(:register_number, "não é válido") unless register_valid_to_eq?(register_number.to_s)

  end

  def register_valid_to_eq?(register)
    first_12_numbers = register[0..11]
    first_digit = digit(digit_calculator(first_12_numbers)).to_s
    second_digit = digit(digit_calculator(first_12_numbers + first_digit)).to_s
    register == first_12_numbers + first_digit + second_digit
  end

  def digit_calculator(number)
    iterator = number.length - 7
    result = 0
    number.each_char do |num|
      result += num.to_i * iterator
      iterator = 10 if iterator == 2
      iterator -= 1
    end
    result%11
  end

  def digit(number)
    return 0 if number < 2
    11 - number
  end



end

app/controllers/api/v1/buffets_controller.rb
class Api::V1::BuffetsController < Api::V1::ApiController
  def index
    
    buffets = Buffet.all.order(brand_name: :asc)
    
    if buffet_params[:brand_name].present?
      buffets = buffets.where('brand_name LIKE ?', "#{buffet_params[:brand_name]}%").order(brand_name: :asc)
      no_content = {'message' => "Sem resultados disponíveis para: #{buffet_params[:brand_name]}"}.to_json
      JSON.parse no_content

      
      return render json: no_content, status: 200 if buffets.empty?
    end


    if buffets.present?
      return render json: buffets.as_json(except: [:created_at, :updated_at]), status: 200
    else
      no_content = {'message' => "Sem resultados disponíveis"}.to_json
      JSON.parse no_content
      render json: no_content, status: 204
    end

  end

  def show
    begin
      buffet = Buffet.find(buffet_show_params[:id])
      render status: 200, json: buffet.as_json(except: [:created_at, :updated_at, :corporate_name, :register_number])
    rescue=> error
      no_content = {'message' => "#{message_format(error.to_s)} parâmetros: buffet.id=#{buffet_show_params[:id]}"}.to_json
      JSON.parse no_content
      render status: 404, json: no_content
    end
  end

  private

  def buffet_params
    params.permit(:brand_name)
  end

  def buffet_show_params
    params.permit(:id)
  end
end

app/controllers/buffet_controller.rb
class BuffetController < ApplicationController

  before_action :authenticate_my_company_owner!
  before_action :redirect_owner_to_home, except: [:create, :update]

  def show
    return redirect_to root_path, alert: 'Acesso não autorizado' unless permited_owner_edit?
    @buffet = Buffet.find(params[:id])
    @events = Event.where(buffet: @buffet)
  end

  def new
    if Buffet.find_by(owner: current_my_company_owner).nil?
      @buffet = Buffet.new 
    else
      flash.alert = 'Buffet já cadastrado' if request.path == new_buffet_path
      redirect_to buffet_path(Buffet.find_by(owner: current_my_company_owner))
    end
  end

  def create
    owner = current_my_company_owner

    @buffet = Buffet.new(buffet_params)
    @buffet.payment_methods = payment_methods_params
    @buffet.owner = owner
    
    if @buffet.save
      flash.notice = "Buffet salvo com sucesso!"
      redirect_to buffet_path(@buffet)
    else
      flash.alert = 'Não foi possível salvar seu Buffet.'
      render 'new'
    end
  end

  def edit
    return redirect_to root_path, alert: 'Acesso não autorizado' unless permited_owner_edit?
    @buffet = Buffet.find(params[:id])
  end

  def update
    return redirect_to root_path, alert: 'Acesso não autorizado' unless permited_owner_edit?
    @buffet = Buffet.find(params[:id])
    @buffet.payment_methods = payment_methods_params
    
    
  
    return redirect_to buffet_path(@buffet), notice: "Buffet atualizado com sucesso!" if @buffet.update(buffet_params)

    flash.alert = 'Não foi possível atualizar seu Buffet.'
    render 'edit'

  end

  def orders
    begin
      @buffet = Buffet.find(params[:buffet_id])
      return redirect_to root_path, alert: 'Acesso não autorizado' unless @buffet.owner == current_my_company_owner
      @orders_waiting_review = Order.waiting_review.where('buffet_id = ?', @buffet.id).order(estimated_date: :asc).group_by { |date| date.estimated_date }
      @other_orders = Order.not_waiting_review.where('buffet_id = ?', @buffet.id).order(estimated_date: :asc).group_by { |date| date.estimated_date }
    rescue
      redirect_to root_path, notice: 'Requisição inválida'
    end
  end

  def order_view
    begin
      return redirect_to root_path, alert: 'Acesso não autorizado' unless is_owner?
      @order = Order.find(params[:id])
      @buffet = @order.buffet
      @event = @order.event
      @price_event = PriceEvent.find_by(event: @event)
      @order_count = Order.not_canceled.where('estimated_date = ? AND buffet_id = ?', @order.estimated_date, @order.buffet_id
                                  ).where('estimated_date >= ?', Date.today)

      @price_order = PriceOrder.find_by(order: @order) if @order.price_order.present?
    rescue
      redirect_to root_path, notice: 'Requisição inválida'
    end


  end

  def confirm_order
    result = params_confirm
    @order = Order.find(result[:id])
    @buffet = @order.buffet
    return redirect_to root_path, alert: 'Acesso não autorizado' unless is_owner?

    case result[:status]
    when 'confirmed' 
      @order.confirmed_for_buffet!
      redirect_to order_view_path(@order), notice: 'Pedido confirmado'
    when 'canceled'
      @order.canceled!
      redirect_to order_view_path(@order), notice: 'Pedido cancelado'
    else
      redirect_to orders_view_path, notice: 'Requisição inválida'
    end

  end

  private

  def buffet_params
    params.require(:buffet).permit(:brand_name, :corporate_name, :city, :state, 
    :address, :register_number, :phone_number, :district, :zip_code,
    :description)
  end

  def payment_methods_params
    methods = params.require(:buffet).permit(payment_methods: [])[:payment_methods]
    if methods.present?
      methods.join(', ') 
    end
  end

  def permited_owner_edit?
    begin
      @buffet = Buffet.find(params[:id])
      @buffet.owner == current_my_company_owner
    rescue
      false
    end
  end

  def is_owner?
    @order = Order.find(params[:id])
    @buffet = @order.buffet
    @buffet.owner == current_my_company_owner
  end

  def params_confirm
    params.permit(:id, :status)
  end
end

app/controllers/buffets/owners/confirmations_controller.rb
# frozen_string_literal: true
module Buffets
  class Owners::ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/buffets/owners/omniauth_callbacks_controller.rb
  # frozen_string_literal: true
module Buffets
  class Owners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/buffets/owners/passwords_controller.rb
  # frozen_string_literal: true
module Buffets
  class Owners::PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/buffets/owners/registrations_controller.rb
  # frozen_string_literal: true
module Buffets
  class Owners::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/buffets/owners/sessions_controller.rb
# frozen_string_literal: true
module Buffets
  class Owners::SessionsController < Devise::SessionsController
    before_action :redirect_owner, except: [:destroy]
  # before_action :configure_sign_in_params, only: [:create]

    def after_sign_in_path_for(resource)
      new_buffet_path
    end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  end
end

app/controllers/buffets/owners/unlocks_controller.rb
  # frozen_string_literal: true
module Buffets
  class Owners::UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/buffets/price_event_controller.rb
class Buffets::PriceEventController < ApplicationController
  def new
    @price_event = PriceEvent.new
    @event = Event.find(params[:format])
  end

  def create

    @event = Event.find(params[:format])
    @buffet = Buffet.find(@event.buffet_id)
    @price_event = PriceEvent.new(price_event_params)
    @price_event.event_id = @event.id
    if @price_event.save
      redirect_to buffets_buffet_path(@buffet)
      return flash.notice = 'Valores salvos com sucesso!'
    end
  end

  private
    def price_event_params
      params.require(:price_event).permit(:min_price_working_day, :additional_price_for_person_working_day, :additional_price_for_person_weekend, :min_price_weekend,
                                    :extra_hour_weekend, :extra_hour_working_day )
    end

end

app/views/buffet/_confirm_order.html.erb
<% case @order.status %>
<% when 'waiting_review' %>
  <div>Confirme o seu pedido</div>
  <div>
    <%= button_to 'Confirmar', confirm_order_path(@order, 'confirmed'), method: :post %>
    <%= button_to 'Cancelar', confirm_order_path(@order, 'canceled'), method: :post %>
  </div>
<% when 'canceled' %>
  <p>Pedido cancelado</p>
<% when 'confirmed_for_buffet' %>
  <p>Aguardando confirmação</p>
<% else %>
  
<% end %>

app/views/buffet/_form.html.erb
<%= form_with model: buffet, url: url, method: method do |form| %>
  <div>
    <%= form.label :brand_name %>
    <%= form.text_field :brand_name %>
  </div>

  <div>
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div>
    <%= form.label :register_number %>
    <%= form.text_field :register_number %>
  </div>

  <div>
    <p><%= form.label :phone_number %> Código de área mais telefone</p>
    <p><%= form.text_field :phone_number %> Somente números</p>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :payment_methods %>
    <% Buffet::METHODS.each do |m| %>
      <div>
        <%= form.check_box :payment_methods, { multiple: true }, Buffet.human_attribute_name(m), nil %> 
        <%= form.label m %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit 'Gravar' %>
  </div>
<% end %>

app/views/buffet/_order_details.html.erb
<section>
  <p><%= Order.human_attribute_name :client %> <%= @order.client.name %></p>
  <p><%= Order.human_attribute_name :estimated_date %> <%= I18n.l @order.estimated_date %></p>
  <p><%= Order.human_attribute_name :estimated_people %> <%= @order.estimated_people %></p>
  <p><%= Order.human_attribute_name :details %> <%= @order.details %></p>
  <p><%= Order.human_attribute_name :address %> <%= @order.address %></p>
</section>

app/views/buffet/_price_order_details.html.erb
<div><%= PriceOrder.human_attribute_name :initial_price %> <%= number_to_currency @price_order.initial_price %></div>

<div><%= PriceOrder.human_attribute_name :final_price %> <%= number_to_currency @price_order.final_price %></div>

<div><%= PriceOrder.human_attribute_name :deadline %> <%= I18n.l @price_order.deadline %></div>

<div><%= PriceOrder.human_attribute_name :rate %> de <%= number_to_currency @price_order.rate %> | 
<%= PriceOrder.human_attribute_name :description_rate %>: <%= @price_order.description_rate %> </div>

<div><%= PriceOrder.human_attribute_name :payment_methods %>: <%= @price_order.payment_methods %> </div>

app/views/buffet/edit.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > Editar dados do Buffet </p>

<h2>Edite seu Buffet</h2>

<% if @buffet.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @buffet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


  <%= render partial: 'form', locals: { buffet: @buffet, url: buffet_path, method: :patch } %>

app/views/buffet/new.html.erb
<% if @buffet.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @buffet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<main>
  <h2>Cadastre seu Buffet</h2>
  <%= form_with model: @buffet, url: buffet_index_path, method: :post do |form| %>
    <div>
      <%= form.label :brand_name %>
      <%= form.text_field :brand_name %>
    </div>

    <div>
      <%= form.label :corporate_name %>
      <%= form.text_field :corporate_name %>
    </div>

    <div>
      <%= form.label :register_number %>
      <%= form.text_field :register_number %>
    </div>

    <div>
      <p><%= form.label :phone_number %> Código de área mais telefone</p>
      <p><%= form.text_field :phone_number %> Somente números</p>
    </div>

    <div>
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div>
      <%= form.label :district %>
      <%= form.text_field :district %>
    </div>

    <div>
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div>
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div>
      <%= form.label :zip_code %>
      <%= form.text_field :zip_code %>
    </div>

    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :payment_methods %>
      <% Buffet::METHODS.each do |m| %>
        <div>
          <%= form.check_box :payment_methods, { multiple: true }, Buffet.human_attribute_name(m), nil %> 
          <%= form.label m %>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.submit 'Gravar' %>
    </div>
  <% end %>
</main>

app/views/buffet/order_view.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > <%= link_to 'Pedidos', buffet_my_orders_path(@event.buffet)%> > <%= "Pedido #{@order.code}" %></p>
<h2><%= Order.model_name.human %> <%= @order.code %> <%= Order.human_attribute_name @order.status%></h2>
<% if @order_count.any? && @order_count.count > 1%>
  <div>
    <p>Existem <%=@order_count.count%> pedidos agendados para está data</p>
    <% @order_count.each do |order| %>
      <p> Order.human_attribute_name :order <%= link_to order.code, order_view_path(order) %>, <%= Order.human_attribute_name order.status %></p>
    <% end %>
  </div>
<% end %>

<p><%= link_to @order.event.name, event_path(@order.event) %></p>
<%= render 'order_details'%>

<% if @order.price_order.present? %>
  <%= render 'price_order_details' %>
  <%= render 'confirm_order' %>
<% else %>
  <p>Valor final ainda não confirmado</p>
  <%= link_to 'Cadastrar novo valor', new_price_order_path(@order)%>
<% end %>

      

app/views/buffet/orders.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > Pedidos</p>
<h2>Pedidos aguardando avaliação</h2>

<% if @orders_waiting_review.any? %>
  <dl>
  <% @orders_waiting_review.each_pair do |date, orders| %>
    <dt><%= I18n.l date %></dt>
      <% orders.each do |order| %>
        <dd><%=Order.human_attribute_name :code%> <%= link_to "#{order.code}", order_view_path(order) %></dd>
      <% end %>
      <br>
  <% end %>
  </dl>
<% else %>
    <p>Não existem pedidos a serem avalidos</p>
<% end %>

<% if @other_orders.any? %>
  <h2>Demais pedidos</h2>
  <dl>
    <% @other_orders.each_pair do |date, orders| %>
      <dt><%= I18n.l date %></dt>
        <% orders.each do |order| %>
          <dd><%=Order.human_attribute_name :code%> <%= link_to "#{order.code}", order_view_path(order) %></dd>
        <% end %>
        <br>
    <% end %>
  </dl>
<% end %>

app/views/buffet/show.html.erb
<p>Meu Buffet</p>
<ul>
  <li><%= @buffet.full_register %></li>
  <li><%= @buffet.full_address %></li>
  <li><%= @buffet.full_contact %></li>
</ul>

<%= link_to 'Editar dados do Buffet', edit_buffet_path(@buffet)%>

<section>
  <% if @events.any? %>
  <table>
  <thead>
    <tr>
      <th>Evento</th>
      <th>Descrição</th>
    </tr>
  </thead>
    <tbody>
      <% @events.each do |ev| %>
        <tr>
          <td><%= link_to "#{ev.name}", event_path(ev) %></td>
          <td><%= ev.description %></td>
        </tr>
      <% end %>
    <tbody/>
  </table>
  <% else %>
    <p>Não existem eventos Cadastrados</p>
  <% end %>
</section>

<%= link_to 'Cadastrar novo evento', new_event_path %>