config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
 

  resources :home, only: %i[show] do 
    resources :orders, only: %i[new create]
    get 'list', on: :collection
    get 'search', on: :collection
    get 'new_order', on: :collection
  end
  
  resources :orders, only: %i[index show] do
    get 'confirmed', on: :collection
    post 'confirm_event/:status', to: 'orders#confirm_event', as: 'confirm_event'
  end


  namespace :my_company do
    devise_for :owners, controllers: {
      sessions: 'my_company/owners/sessions',
      confirmations: 'my_company/owners/confirmations',
      omniauth: 'my_company/owners/omniauth',
      passwords: 'my_company/owners/passwords',
      registrations: 'my_company/owners/registrations',
      unlocks: 'my_company/owners/unlocks'
    }
  end

  resources :buffet, only: %i[show new create edit update] do
    get 'orders', to: 'buffet#orders', as: 'my_orders'
  end
  
  scope :orders_for_owner do
    get 'order_view/:id', to: 'buffet#order_view', as: 'order_view' 
    post 'confirm_order/:id/:status', to: 'buffet#confirm_order', as: 'confirm_order'

    get 'new_price_order/:id', to: 'price_orders#new', as: 'new_price_order'
    post 'price_orders/:id', to: 'price_orders#create', as: 'price_orders'
  end

  resources :events, only: %i[new create show edit update] do
    resources :price_events, only: %i[new create]
    get 'historic_orders', to: 'events#historic_orders', as: 'historic_orders'
  end

  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    confirmations: 'clients/confirmations',
    omniauth: 'clients/omniauth',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    unlocks: 'clients/unlocks'
  }
  



  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index]
      end
      resources :events, only: %i[show] do
        get 'avaliable_event', on: :member
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_owner, only: %i[index]
  before_action :authenticate_client!, only: %i[new_order]
  def index
  end

  def list
    buffets = Buffet.order(brand_name: :asc).all
    @ordened_buffets = buffets.group_by { |first_char| first_char.brand_name[0].upcase }
    @ordened_buffets
  end

  def show
    @buffet = Buffet.find(params[:id])
    @events = Event.where(buffet: @buffet)
  end

  def search
    @q = params[:query]
    buffets = Buffet.order(brand_name: :asc).where('brand_name like ? OR city like ? OR description like ?', "%#{@q}%",
                "%#{@q}%", "%#{@q}%")

    @ordened_buffets = buffets.group_by { |first_char| first_char.brand_name[0].upcase }
    @ordened_buffets
  end

  def new_order
    @events = Event.order(name: :asc).all
  end

  private

  def authenticate_owner
    @buffet = Buffet.find_by(owner: current_my_company_owner)
    redirect_to buffet_path(@buffet) if my_company_owner_signed_in?
  end
end

app/views/home/_results.html.erb
<% if @ordened_buffets.present? %>
  
  <section>
    <ul>
      <% @ordened_buffets.each_pair do |alphabetical_order, buffets| %>
        <li><%= alphabetical_order %>
          <% buffets.each do |buffet|%>
            <dl><%= Buffet.model_name%> <%= link_to "#{buffet.brand_name}", home_path(buffet)%></dl>
              <dd><%= Buffet.human_attribute_name :address%>: <%= buffet.city%> - <%= buffet.state%></dd>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>

<% else %>
  <p>Não foram localizados Buffets</p>
<% end %>

app/views/home/_show_event.html.erb
<% if @events.present? %>
   

  <h3>Eventos</h3>
  <ul>
    <% @events.each do |event| %>
      <li>
        <% if client_signed_in? %>
          <h3><%= link_to "Novo pedido - #{event.name}", new_home_order_path(event.id) %> </h3>
        <% end %>
        <div><p><%= event.full_description %></p></div>

        <div><p><%= event.capacity %></p></div>

        <div><p><%= event.duration %></p></div>

        <div><p><%= event.menu_description %></p></div>

        <div><p><%= event.alcoholic? %></p></div>

        <div><p><%= event.decoration? %></p></div>

        <div><p><%= event.parking_space? %></p></div>

        <div><p><%= event.valet_service? %></p></div>

        <div><p><%= event.location? %></p></div>

        <% ev_p = PriceEvent.find(event.price_events) %>
        <div><p><%= ev_p.price_working_days(number_to_currency(ev_p.min_price_working_day), 
        number_to_currency(ev_p.additional_price_for_person_working_day),
        number_to_currency(ev_p.extra_hour_working_day)) %></p></div>

        <div><p><%= ev_p.price_weekend(number_to_currency(ev_p.min_price_weekend), 
        number_to_currency(ev_p.additional_price_for_person_weekend),
        number_to_currency(ev_p.extra_hour_weekend)) %></p></div>
    </li>
    <hr>
    <% end %>
  </ul>
<% else %>
    <p>Não existem eventos disponíveis no momento</p>

<% end %>

app/views/home/index.html.erb
<p>Home</>
<p>Seja bem-vindo a maior plataforma de Buffets do Brasil!</p>

<p>Venha conhecer nossos serviços de consultoria.</p>

app/views/home/list.html.erb
<p><%= link_to 'Home', root_path%> > Listar Buffets</p>

<%= render 'results' %>

app/views/home/new_order.html.erb
<h2>Selecione o evento desejado</h2>

<%= render 'show_event' %>

app/views/home/search.html.erb
<p><%= link_to 'Home', root_path%> > Busca por: <%= @q %></p>

<%= render 'results' %>

app/views/home/show.html.erb
<p><%= link_to 'Home', root_path %> > <%= link_to 'Listar Buffets', list_home_index_path%> > <%= "#{@buffet.brand_name}"%></p>

<h2><%= Buffet.model_name %></h2>
<ul>
  <li><%= @buffet.brand_name %> | CNPJ: <%= @buffet.register_number%> | Telefone: <%=@buffet.phone_number%></li>
  <li><%= @buffet.full_address %></li>
  <li><%= @buffet.full_contact %></li>
  

    <%= render 'show_event'%>

</ul>