config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
 

  resources :home, only: %i[show] do 
    resources :orders, only: %i[new create]
    get 'list', on: :collection
    get 'search', on: :collection
    get 'new_order', on: :collection
  end
  
  resources :orders, only: %i[index show] do
    get 'confirmed', on: :collection
    post 'confirm_event/:status', to: 'orders#confirm_event', as: 'confirm_event'
  end


  namespace :my_company do
    devise_for :owners, controllers: {
      sessions: 'my_company/owners/sessions',
      confirmations: 'my_company/owners/confirmations',
      omniauth: 'my_company/owners/omniauth',
      passwords: 'my_company/owners/passwords',
      registrations: 'my_company/owners/registrations',
      unlocks: 'my_company/owners/unlocks'
    }
  end

  resources :buffet, only: %i[show new create edit update] do
    get 'orders', to: 'buffet#orders', as: 'my_orders'
  end
  
  scope :orders_for_owner do
    get 'order_view/:id', to: 'buffet#order_view', as: 'order_view' 
    post 'confirm_order/:id/:status', to: 'buffet#confirm_order', as: 'confirm_order'

    get 'new_price_order/:id', to: 'price_orders#new', as: 'new_price_order'
    post 'price_orders/:id', to: 'price_orders#create', as: 'price_orders'
  end

  resources :events, only: %i[new create show edit update] do
    resources :price_events, only: %i[new create]
    get 'historic_orders', to: 'events#historic_orders', as: 'historic_orders'
  end

  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    confirmations: 'clients/confirmations',
    omniauth: 'clients/omniauth',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    unlocks: 'clients/unlocks'
  }
  



  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index]
      end
      resources :events, only: %i[show] do
        get 'avaliable_event', on: :member
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner
  belongs_to :buffet
  has_many :price_events
  has_many :orders
  has_many :price_orders, through: :orders
  accepts_nested_attributes_for :price_events




  validates :name, :description, :min_quantity_people, :max_quantity_people, :duration_in_minutes, :menu,
             presence: true

  validates :max_quantity_people, comparison: { greater_than_or_equal_to: :min_quantity_people }

  def full_description
    "#{name} - #{description}"
  end

  def capacity
    return "Capacidade de #{min_quantity_people} à #{max_quantity_people} pessoas" if max_quantity_people > min_quantity_people
    "Capacidade máxima de #{min_quantity_people} pessoa(s)"
  end

  def duration
    "Duração de #{duration_in_minutes} minutos"
  end

  def menu_description
    "Cardápio: #{menu}"
  end

  def alcoholic?
    return "Bebidas alcoólicas disponíveis" if alcoholic_drink
    "Sem bebida alcoólica"
  end

  def decoration?
    return "Decoração própria" if self_decoration
    "Decoração a parte"
  end

  def parking_space?
    return "Estacionamento disponível" if parking
    "Sem estacionamento"
  end

  def valet_service?
    return "Valet disponível" if valet
    "Sem valet"
  end

  def location?
    return "Local fixo" if fixed_location
    "Local flexível"

  end

  
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::ApiController
  def index
    begin
      buffet = Buffet.find(params[:buffet_id])
      no_content = {'message' => "Não existem eventos cadastrado para o Buffet: #{buffet.brand_name}"}.to_json
      JSON.parse no_content
      events = Event.where('buffet_id = ?', params[:buffet_id])

      if events.present?
        return render status: 200, json: events.as_json(except: [:created_at, :updated_at]) 
      else
        return render status: 200, json: no_content
      end
    rescue=> error
      no_content = {'message' => "#{message_format(error.to_s)} parâmetros: buffet.id=#{params[:buffet_id]}"}.to_json
      JSON.parse no_content
      render status: 404, json: no_content
    end
  end

  def show
    begin
      event = Event.find(params[:id])
      # event = translatedata(event)
      return render status: 200, json: event.as_json(except: [:created_at, :updated_at])
    rescue => error
      no_content = {'message' => "#{message_format(error.to_s)} parâmetros: event.id=#{params[:id]}"}.to_json
      JSON.parse no_content
      render status: 404, json: no_content
    end
  end

  def avaliable_event
    begin
      event = Event.find(params_event_show[:id])
      estimated_date = params_event_show[:estimated_date]
      quantity_people = params_event_show[:estimated_quantity_people]

      if estimated_date.present? && quantity_people.present?
        result = availability_event_show(event, estimated_date, quantity_people)
        render status: 200, json: result
      else
        error_message = [{'message' => "#{I18n.t :invalid_event} #{event.name}"},
        {"estimated_date_present" => "#{I18n.t :date_event} #{I18n.t estimated_date.present?}"},
        {"estimated_quantity_people_present" => "Número de convidados #{I18n.t quantity_people.present?}"}].to_json

        JSON.parse error_message
      
        render status: 404, json: error_message
      end
      
    rescue=> error
      no_content = {'message' => "#{message_format(error.to_s)} parâmetros: event.id=#{params[:id]}"}.to_json
      JSON.parse no_content
      render status: 404, json: no_content
    end
  end


  private

  def availability_event_show(event, estimated_date, quantity_people)
    quantity_people = quantity_people.to_i
    estimated_date = Date.parse estimated_date
    availability = true
    number_order_avaliable_date = 0
    event.orders.confirmed.each do |order|
      if order.estimated_date == estimated_date
        availability = false 
        number_order_avaliable_date += 1
      end
    end
    availability = false if event.min_quantity_people > quantity_people || event.max_quantity_people < quantity_people

    if availability
      date = estimated_date
      json_response = number_to_currency base_price(event, date, quantity_people)
      result = {'base_price_event' => "#{I18n.t :estimated_price} #{json_response}"}.to_json
      JSON.parse result
      return result
    else
      min_people_params = (event.min_quantity_people <= quantity_people)
      max_people_params = (event.max_quantity_people >= quantity_people)
      available_date = number_order_avaliable_date < 1
      date_format = I18n.l estimated_date


      error_message = [{'message' => "#{I18n.t :false_avaliable_event} #{event.name}"},
        {"min_quantity_people" => "#{I18n.t :estimated_people_min} #{I18n.t min_people_params}, quantidade min.: #{event.min_quantity_people}"},
        {"max_quantity_people" => "#{I18n.t :estimated_people_max} #{I18n.t max_people_params}, quantidade máx.: #{event.max_quantity_people}"},
        {"estimated_date" => "#{I18n.t :date_event} #{I18n.t available_date}"}].to_json

      JSON.parse error_message
    end
  end

  def params_event_show
    params.permit(:estimated_date, :estimated_quantity_people, :id)
  end

  def base_price(event, estimated_date, quantity_people)
    price_event = PriceEvent.find_by(event: event)
    is_weekend = (0 == estimated_date.wday || 6 == estimated_date.wday)
    add_people = 0
    add_people = quantity_people - event.min_quantity_people if quantity_people > event.min_quantity_people

    @initial_price = 0
    if is_weekend 
      @initial_price = price_event.min_price_weekend.to_i + price_event.additional_price_for_person_weekend*add_people
    else
      @initial_price = price_event.min_price_working_day.to_i + price_event.additional_price_for_person_working_day*add_people
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_my_company_owner!
  def show
    return redirect_to root_path, alert: 'Acesso não autorizado' unless is_owner?
    @event = Event.find(params[:id])
    @price = PriceEvent.find(@event.price_events)
  end

  def new
    @event = Event.new
    @price = PriceEvent.new
    @buffet = Buffet.find_by(owner: current_my_company_owner)
  end



  def create
    @buffet = Buffet.find_by(owner: current_my_company_owner)
    @event = Event.new(event_params)
    @event.owner = @buffet.owner
    @event.buffet = @buffet
    
    @price = PriceEvent.new(price_event_params) 
    @price.event = @event

    if @event.valid? && @price.valid?
      @event.save!
      @price.save! 
      return redirect_to buffet_path(@buffet), notice: 'Evento registrado com sucesso!'
    end
      flash.notice = 'Não foi possível cadastrar seu Evento.'
      render 'new'
    
  end


  def edit
    return redirect_to root_path, alert: 'Acesso não autorizado' unless is_owner?
    @event = Event.find(params[:id])
    @price = PriceEvent.find_by(event: @event)
    @buffet = Buffet.find(@event.buffet_id)
  end
  
  def update
    return redirect_to root_path, alert: 'Acesso não autorizado' unless is_owner?
    @event = Event.find(params[:id])
    
    
    @price = PriceEvent.find_by(event: @event)

    if @event.update(event_params) && @price.update(price_event_params)
      flash.notice = 'Evento atualizado com sucesso!'
      return redirect_to buffet_path(@buffet)
    end
      flash.notice = 'Não foi possível atualizar seu Evento.'
      render 'edit'
    

  end

  def historic_orders
    @event = Event.find(params[:event_id])
    @historic = Event.find(params[:event_id]).orders
    return redirect_to root_path, alert: 'Acesso não autorizado' unless  Event.find(params[:event_id]).owner == current_my_company_owner
  end

  private
    def event_params
      params.require(:event).permit(
    :name,
    :min_quantity_people,
    :max_quantity_people,
    :duration_in_minutes,
    :alcoholic_drink,
    :self_decoration,
    :parking,
    :valet,
    :fixed_location,
    :description,
    :menu
    )
  end
  def price_event_params
    params.require(:event).permit(
      price_event: [
        :id,
        :min_price_working_day,
        :min_price_weekend,
        :additional_price_for_person_working_day,
        :additional_price_for_person_weekend,
        :extra_hour_working_day,
        :extra_hour_weekend,
        :_destroy
      ]
    )[:price_event] 
  end

  def is_owner?
    begin
      @event = Event.find(params[:id])
      @event.owner == current_my_company_owner
    rescue
      false
    end
  end

end

app/views/events/_form.html.erb
<section>
  <%= form_with model: @event do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :min_quantity_people %>
      <%= form.number_field :min_quantity_people%>
    </div>
  
    <div>
      <%= form.label :max_quantity_people %>
      <%= form.number_field :max_quantity_people %>
    </div>
  
    <div>
      <%= form.label :duration_in_minutes %>
      <%= form.text_field :duration_in_minutes %>
    </div>
  
    <div>
      <%= form.label :alcoholic_drink %>
      <%= form.check_box :alcoholic_drink %>
    </div>
  
    <div>
      <%= form.label :self_decoration %>
      <%= form.check_box :self_decoration %>
    </div>
  
    <div>
      <%= form.label :parking %>
      <%= form.check_box :parking%>
    </div>
  
    <div>
      <%= form.label :valet %>
      <%= form.check_box :valet %>
    </div>
  
    <div>
      <%= form.label :fixed_location %>
      <%= form.check_box :fixed_location %>
    </div>
  
    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div>
      <%= form.label :menu %>
      <%= form.text_area :menu, value: @event[:menu] %>
    </div>

    <h3>Valores</h3>
      <%= form.fields_for @price do |price| %>
        <div>
        <h4>Dias úteis</h4>
          <div>
            <%= price.label :min_price_working_day %>
            <%= price.number_field :min_price_working_day %>
          </div>
        
          <div>
            <%= price.label :additional_price_for_person_working_day %>
            <%= price.number_field :additional_price_for_person_working_day %>
          </div>
        
          <div>
            <%= price.label :extra_hour_working_day %>
            <%= price.number_field :extra_hour_working_day %>
          </div>
        </div>

        <div>
          <h4>Fins de semana</h4>
          <div>
            <%= price.label :min_price_weekend %>
            <%= price.number_field :min_price_weekend %>
          </div>
        
          <div>
            <%= price.label :additional_price_for_person_weekend %>
            <%= price.number_field :additional_price_for_person_weekend %>
          </div>
        
          <div>
            <%= price.label :extra_hour_weekend %>
            <%= price.number_field :extra_hour_weekend %>
          </div>
        </div>
      <% end %>
      
    <div>
      <%= form.submit 'Registrar' %>
    </div>
  <% end %>
</section>

app/views/events/_show_event.html.erb
<main>
  <h2><%= @event.name %></h2>
  <div><p><%= @event.full_description %></p></div>

  <div><p><%= @event.capacity %></p></div>

  <div><p><%= @event.duration %></p></div>

  <div><p><%= @event.menu_description %></p></div>

  <div><p><%= @event.alcoholic? %></p></div>

  <div><p><%= @event.decoration? %></p></div>

  <div><p><%= @event.parking_space? %></p></div>

  <div><p><%= @event.valet_service? %></p></div>

  <div><p><%= @event.location? %></p></div>

  <div><p><%= @price.price_working_days(number_to_currency(@price.min_price_working_day), 
              number_to_currency(@price.additional_price_for_person_working_day),
              number_to_currency(@price.extra_hour_working_day)) %></p></div>

  <div><p><%= @price.price_weekend(number_to_currency(@price.min_price_weekend), 
              number_to_currency(@price.additional_price_for_person_weekend),
              number_to_currency(@price.extra_hour_weekend)) %></p></div>
</main>

app/views/events/edit.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > <%=link_to "#{@event.name}", event_path(@event)%> > Editar informações </p>

<% if @event.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<% if @price.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @price.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<main>
  <h2>Editar evento <%= @event.name%></h2>
  <%= render 'form' %>
</main>

app/views/events/historic_orders.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > <%= link_to @event.name, event_path(@event) %> > <%= Event.human_attribute_name :historic %>: <%= @event.name %></p>
<h2><%= Event.human_attribute_name :historic %>: <%= @event.name %></h2>
<% if @historic.present? %>
  <% @historic.each do |order| %>
    <dl>
      <dt><%= Order.human_attribute_name :code%> <%= link_to "#{order.code}", order_view_path(order) %></dt>
      <dd><%= Buffet.human_attribute_name :estimated_date%>: <%= I18n.l order.estimated_date %></dd>
      <dd><%= Order.human_attribute_name :status%>: <%= Buffet.human_attribute_name order.status %></dd>
    </dl>
  <% end %>
<% else %>
  <p>Não existem pedidos registrados %>
<% end %>

app/views/events/new.html.erb
<p><%= link_to 'Meu Buffet', buffet_path(@buffet)%> > Cadastrar novo evento</p>

<% if @event.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<% if @price.errors.any? %>
  <p>Reveja os campos abaixo: </p>
  <ul>
  <% @price.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


<main>
  <h2>Cadastrar novo evento</h2>
  <%= render 'form' %>
</main>

app/views/events/show.html.erb
<p><%= link_to 'Voltar', :back%> > <%= @event.name %></p>

<div>
  <%= link_to 'Editar informações', edit_event_path(@event)%>
</div>
<%= link_to 'Histórico de pedidos', event_historic_orders_path(@event) %>
<%= render 'show_event'%>