config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
 

  resources :home, only: %i[show] do 
    resources :orders, only: %i[new create]
    get 'list', on: :collection
    get 'search', on: :collection
    get 'new_order', on: :collection
  end
  
  resources :orders, only: %i[index show] do
    get 'confirmed', on: :collection
    post 'confirm_event/:status', to: 'orders#confirm_event', as: 'confirm_event'
  end


  namespace :my_company do
    devise_for :owners, controllers: {
      sessions: 'my_company/owners/sessions',
      confirmations: 'my_company/owners/confirmations',
      omniauth: 'my_company/owners/omniauth',
      passwords: 'my_company/owners/passwords',
      registrations: 'my_company/owners/registrations',
      unlocks: 'my_company/owners/unlocks'
    }
  end

  resources :buffet, only: %i[show new create edit update] do
    get 'orders', to: 'buffet#orders', as: 'my_orders'
  end
  
  scope :orders_for_owner do
    get 'order_view/:id', to: 'buffet#order_view', as: 'order_view' 
    post 'confirm_order/:id/:status', to: 'buffet#confirm_order', as: 'confirm_order'

    get 'new_price_order/:id', to: 'price_orders#new', as: 'new_price_order'
    post 'price_orders/:id', to: 'price_orders#create', as: 'price_orders'
  end

  resources :events, only: %i[new create show edit update] do
    resources :price_events, only: %i[new create]
    get 'historic_orders', to: 'events#historic_orders', as: 'historic_orders'
  end

  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    confirmations: 'clients/confirmations',
    omniauth: 'clients/omniauth',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    unlocks: 'clients/unlocks'
  }
  



  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index]
      end
      resources :events, only: %i[show] do
        get 'avaliable_event', on: :member
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadeBuffet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
      * {
        margin-bottom: 0;
        border-radius: 1;
        margin-left: 1rem;
      }

      .navbar ul li {
        display: flex;
      }
      
      button{
        background: #0066A2;
        color: white;
        border-style: outset;
        border-color: #0066A2;
        height: 30px;
        width: 60px;
        font: bold15px arial,sans-serif;
        text-shadow: none;
      }

      ul li, p, h2, h3, table {
        margin: 1rem;
      }

    </style>
  </head>

  <body>
  <h1><%= link_to 'Cadê Buffet', root_path%></h1>

  <%= form_with url: search_home_index_path, method: :get do %>
    <%= label_tag :query, 'Busca:' %>
    <%= text_field_tag :query %>
    <%= submit_tag 'Buscar' %>
  <% end %>

  <div>
    <h2>Veja nossos Buffets cadastrados</h2>
    <div><%= link_to 'Listar Buffets', list_home_index_path %></div>
  </div>
  

  <% if my_company_owner_signed_in? || client_signed_in? %>

    <% if my_company_owner_signed_in? %>
      <nav class=" navbar">
        <ul>
          <li>
            <%= link_to 'Pedidos', buffet_my_orders_path(Buffet.find_by(owner_id: current_my_company_owner.id)) if Buffet.find_by(owner_id: current_my_company_owner.id).present? %>
            <%= button_to 'Sair', destroy_my_company_owner_session_path, method: :delete %>
          </li>
        </ul>
      </nav>

    <% else %>
      <p><%= current_client.name%> - <%= Client.find(current_client.id).register_mask %></p>
      <nav class="navbar">
        <ul>
          <li><%= link_to 'Meus pedidos', orders_path %>
          <%= link_to 'Novo pedido', new_order_home_index_path %>
          <%= link_to 'Pedidos confirmados', confirmed_orders_path if Order.where('client_id = ? AND status = ?', current_client.id, '2')%>
          <%= button_to 'Sair', destroy_client_session_path, method: :delete %></li>
        </ul>
      </nav>
    <% end %>
    
  <% else %>
    <nav class="navbar">
      <ul>
        <li><%= link_to 'Sou Proprietário', new_my_company_owner_session_path %>
        <%= link_to 'Sou Cliente', new_client_session_path %></li> 
      </ul>  
    </nav>
  <% end %>

    <div>
      <%= notice %>
    </div>

    <div>
      <%= alert %>
    </div>

    <%= yield %>
  </body>
</html>